### ISSUE TITLE
☂ Remove the TSUrlHttpParamsGet and TSUrlHttpParamsSet APIs for 10.x

### ISSUE THREAD

**Issue by bryancall** [apache/trafficserver#11566]
**Note:** Make sure to mark all PRs with an "Incompatible" Label.

**TSUrlHttpParamsGet**
- [x] cookie remap (@bryancall) [#11579]
- [x]  stale reqponse (@bneradt) [#11572]
- [x] header rewrite (@zwoop) [#11570]
- [x]  lua (@shukitchan) [#11580]
- [x] regex_remap (@zwoop) [#11571]
- [x] s3 auth (@maskit) [#11586]
- [x] Cripts (@zwoop) [#11569]

**TSUrlHttpParamsSet**
- [x] Cripts (@zwoop)
- [x] lua (@shukitchan) [#11580]
- [x] url sig (@ezelkow1) [#11599]

**Overall**
- [x] remove docs for TSUrlHttpParamsGet [#11587]
- [x] remove APIs [#11624]

**Comment by bryancall** [comment]
@maskit is going to send email to the dev@ mailing list talking about our decision to remove these APIs for 10.x

**Comment by shukitchan** [comment]
yeah. I will do my bit before end of the week

**Comment by maskit** [comment]
All the todo were done.
