### ISSUE TITLE
⛱ draft-12 (+ PR1389) Series Support

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#3830]
"draft-12 + PR1389" is target of 6th Implementation Draft.
- https://github.com/quicwg/base-drafts/wiki/6th-Implementation-Draft
- https://tools.ietf.org/rfcdiff?url2=draft-ietf-quic-transport-12.txt

## TODOs
- [ ] Enable server to transition connections to a preferred address
- [x] Packet numbers are encrypted
- [x] Packet numbers use a variable-length encoding
- [x] STREAM frames can now be empty
- [x] Make the packet number encryption sampling clearer (PR1389)

**Comment by maskit** [comment]
I'm working on packet number encryption.

**Comment by maskit** [comment]
PNE and PR1389 are supported now (0e2934c).

**Comment by masaori335** [comment]
Handling empty stream frame is done by c11c12e3020e2bf4328c6a6df9a58c93ae7f6390

**Comment by masaori335** [comment]
We'll add Server's Preferred Address support later. (added on the ToDo column on the project page)
