### ISSUE TITLE
⛱ SSLUtils Cleanups

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#5040]
This is collection of TODOs and PRs for SSLUtils cleanups.

### TODOs

- [x] Introduce `SSLMultiCertConfigLoader`
- [x] Drop old OpenSSL support

### TODOs (later)

- [ ] Replace the Tokenizer with a stringview/textview based parser.
https://github.com/apache/trafficserver/pull/5032/files#r258525159
- [ ] Tidy up TLS Session Ticket code > https://github.com/apache/trafficserver/pull/5054#discussion_r259683729
- [ ] Slice `SSLMultiCertConfigLoader::init_server_ssl_ctx` depends on features - e.g. session cahce, alpn, sni.
