### ISSUE TITLE
 ☂ Make C-APIs require C++ compiler

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#5360]
- [x] Change compiler options of all plugins to be c++, optionally rename .c files to .cc ?
- [x] Assure that when including ts/ts.h, we have a C++ compiler
- [x] Eliminate all tests around being in C compiler state
- [x] Fix tsxs to only work with C++ compilers (fail / error if not)
- [ ] Consider what "internal" C++ include files can and should be made public includes
- [ ] Cleanup the mess with libswoc in two places
- [ ] Break out APIs into its own .so
- [ ] Namespaces

The goal is not to break the C-API, but to enforce that a C++ compiler is always used going forward.

**Comment by zwoop** [comment]
Blocks: #5457

**Comment by zwoop** [comment]
Deferring this to v10.0.0, since there's little interest, and some opposition. The C-APIs will stay C for the next 2-3 years.

**Comment by ywkaras** [comment]
I think https://github.com/apache/trafficserver/pull/10007 (already merged) basically accomplished this, but I suppose some tweaks may be needed.

**Comment by ywkaras** [comment]
It was a great day when I stopped using tsxs.  I know how Dorothy felt when Glenda told her to just tap the damn shoes together.

**Comment by ywkaras** [comment]
Isn't Chris working on breaking out the APIs into .so files?  For all the "cleanup" things, can you elaborate on what you want?

**Comment by ywkaras** [comment]
Since ts.h has C++ code in it (namespaces for example), it will give errors if you try to compile it as C.  Did you also want a check for `__cplusplus >= 201703L` ?  It ts.h won' t compile, tsxs will get an error, so I don't understand what I should change in tsxs.

**Comment by ywkaras** [comment]
I don't know how to do the libswoc fix.
