### ISSUE TITLE
 ☂ Plugins to remove for v9.0.0

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#5395]
- [x] balancer
- [x] buffer_upload (or promote)
- [x] header_normalize
- [x] hipes
- [ ] memcache, but make an example plugin
- [x] memcached_remap
- [ ] mysql_remap: Mark as deprecated for v9.0.0, remove / rewrite in 10.0.0
- [x] stale_while_revalidate (deprecated, should remove code)

**Comment by zwoop** [comment]
This list also needs to be vetted on the mailing list.

**Comment by zwoop** [comment]
Blocks #5457

**Comment by chuyenim** [comment]
> * [ ]  mysql_remap
> *

How can I make dynamic remaps without mysql_remap plugin?

**Comment by zwoop** [comment]
If you need the behavior, we should implement something different. The mySQL APIs are blocking, and it's a really bad idea to use with ATS. We should just not have plugins with such bad behavior.

**Comment by SolidWallOfCode** [comment]
How dynamic do the remaps need to be? You could write a config and then use a plugin message to signal a config reload. We're using a similar technique internally.

**Comment by SolidWallOfCode** [comment]
Another approach is to use REDIS with an external process that loads the data. I think the SSL session reuse plugin demonstrates how to do that.

**Comment by zwoop** [comment]
Yes, something other than the blocking mySQL APIs would be preferable :). Even a sqlite implementation would likely be better.

**Comment by igalic** [comment]
what about balancer? do we have a good story how to "replace" that?

**Comment by mlibbey** [comment]
From the balancer plugin page
https://docs.trafficserver.apache.org/en/latest/admin-guide/plugins/balancer.en.html
"Note: All of the the features in this plugin (and more) are found in parent.config. As a result, this plugin is likely to be deprecated"
