### ISSUE TITLE
☂ Action items prior to July 9.x branch

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#5457]
These are general open issues, that needs to be dealt with. For specific Issues, just comment on the issue with a "Blocks #5457".

- [x] Triage all open issues (prioritize)
- [x] Triage all open PRs
- [x] Fix outstanding clang-analyzer issues
- [x] Merge QUIC branch [#5580]
- [x] Merge parent.yaml [#4857]
- [x] New Parent / Next hop selection services (Issue/PR?)
- [x] Merge ip_allow.yaml [#4168]
- [x] Merge Voluspa [#4436]
- [x] C-APIs -> C++ [#5360]
- [x] Unify the YAML name space
- [x] Review, and update, the cipher suite defaults [#2997]
- [x] Consider turning off TLS v1.1 by default
- [x] Consider removing remaining SSL v3 code
- [x] Run clang-tidy over the entire code base again
- [x] Plugin promotion and removal [#5394] [#5395]
- [x] Remove filenames in records.config [#5363]
- [x] Reloadable plugins [#5282]
- [x] Removed ssl.wire_trace feature [#4652]
