### ISSUE TITLE
 ☂ Remove use of TSConfig

### ISSUE THREAD

**Issue by randall** [apache/trafficserver#5471]
For 9.x, we should remove the remaining usages of TSConfig.

- [x] Remove use of TSConfig from ssl_preaccept (#5455)
- [x] Convert traffic_wccp to YAML (#5470)
- [ ] Remove TSConfig classes
- [ ] Move ts:Errata somewhere else

**Comment by zwoop** [comment]
Blocks #5457

**Comment by zwoop** [comment]
Maybe I'm missing it, but shouldn't there be a top-level tag such as

```
wccp:
```

**Comment by randall** [comment]
You're right. Added!
