### ISSUE TITLE
☂ QUIC Todo for 9.0

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#5580]
# Port non-QUIC code changes to master
- [x] Add HKDF wrapper (@maskit) - #5480
- [x] Move common header compression logic (@maskit) - #5465
- [x] UDP layer optimization 04dfc12f56e034d041789a3d2ebbbdf069a10f44 (@scw00) - #5588
- [x] MT_hashtable interface change (@maskit) - #5664
- [x] UDP packet dest address (@maskit) - #5704
- [x] Update test_UDPNet e5a65d77da2d2f3b50ca5be7930488352ae896bb (@masaori335) - #5615
- [x] Add ats_unique_buf #5673

# Fix critical issues
- [x] Clang-analyzer failure #5663

# Cleanup
- [x] Run clang-tidy (4b8151ad413419ad94b6a7c1327eb7b95ee4d13c)
- [x] Make gcc9 friendly (4b8151ad413419ad94b6a7c1327eb7b95ee4d13c)

# Final step
- [x] Branch quic-20 and make a PR against master
- [x] Merge the PR - ~#5594~ #5753

**Comment by zwoop** [comment]
Lets make this happen sooner rather than later :) You still have the opportunity to recommend PRs from master to the 9.0.0 branch as well.

**Comment by maskit** [comment]
Yeah, I'd love to. I'm waiting for feedback and approvals for the PR on the todo list. Once the PRs have been merged, I can do the cleanup and make a PR soon. These steps should be a piece of cake (actually I did the cleanup once, so I just need to double-check if it's still fine).

**Comment by maskit** [comment]
Done!
