### ISSUE TITLE
☂ v9.0.0 Release Stoppers

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#5932]
**Issues**
- [x] 9.0.x Inactivity Cop Crash #7338
- [x] 9.0.x use-after-free crash #7333
- [x] 9.0: proxy.process.http.current_client_transactions metric is broken #7163
- [x] Regression: ATS 9.0.x served cached objects with a negative CC: max-age #7254
- [x] Regression: ATS 9.0.x rejects URI's with two leading /'s #7246
- [x] Crash due to bug in Thread Context migration #7096 - PR #7278 
- [x] ATS 9.0.x release notes
- [x] Logging continuously tries to delete logs #7242
- [x] Rolled logs are not removed when max_space_mb reached #7204
- [x] proxy.config.http.number_of_redirections with hit_stale #7200
- [x] Strip whitespace between field-name and the : #7176
- [x] 9.0.0 - core in PluginFactory::indicatePostReload() #7094
- [x] Loop detection interferes with parent selection #7052
- [x] Warning in HostDBContinuation::set_check_pending_dns #7164
- [x] 9.0.x Crash in BaseLogFile #7017
- [x] 9.0: proxy.process.http.current_client_connections metric is broken #7054
- [x] header_rewrite CLIENT-URL using the remaped to url #7024
- [x] Cleanup of old 9.0.0 code #7020
- [x]  Assertion in HTTP/2  #4119
- [x] Crash on HttpSM::state_http_server_open() #6510 
- [x] Crash in Http1ClientSession::free (triggered via authproxy plugin) #6527
- [x] ATS9 crash on inactivity timeout #6924
- [x] ATS9 Crash in http_hdr_clone #6882
- [x] Plugin memory leak with TSMutexCreate #5777
- [x] Log files are not being cleaned up  #5966
- [x] ATS9: performance regression #6178
- [x] Crash in DNS #5933
- [x] ASAN heap-use-after-free in HttpVCTable::remove_entry #5807
- [x] ATS 9 NetHandler lock abort #5943
- [x] ATS 9 using a continuation which is deleted #5944
- [x] crash reloading parent.config on ATS 9 #5976
- [x] ASAN in InactivityCop #6313
- [x] Assertion with fail_action=5 #6428

**Pull Requests**
- [ ] Handle Transfer-Encoding as a hop-by-hop header #6908
- [x] Fix bad HTTP/2 post client causing stuck HttpSM #7237
- [ ] Reset stale read.triggered when migrating thread contexts #7097 
- [x] Preserve cert name through ssl migration #6977
- [x] Prevent buffer overflow during log filter actions #6950 
- [x] Load combined file with bogus key path #6933
- [x] Improve client_vc tracking #6889
- [x] Disable max_connections_active_in default and fix close logic #6903
- [x] Set of next-hop back ports #6256
- [x] SSL session cache issues #5935
- [x] Address pipe remove on reload and add pipe reuse #6017

**Comment by randall** [comment]
I would recommend adding https://github.com/apache/trafficserver/issues/5976 and https://github.com/apache/trafficserver/issues/5777 as blockers for 9.0.0

**Comment by calavera** [comment]
@zwoop was this issue removed? the link goes to the 404 page for me:

>  Assertion in HttpSM (regression) #4921

**Comment by randall** [comment]
@calavera That was an issue @thelounge-zz filed, but it looks like his account has been deleted (https://github.com/thelounge-zz 404s).

**Comment by thelounge-zz** [comment]
github flagged my account....
