### ISSUE TITLE
☂ Cherry-pick next hop selection PR suite to v9.0.x

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#6256]
Creating this issue to track all the dependencies etc. for this feature.

- [ ] #5960 - Add Nexthop selection strategies and @strategy tag to remap.config.
- [ ] #6206 - Fix the strategies.yaml documentation.
- [ ] #6208 - Fixes spelling in strategies.yaml docs
- [ ] #6210 - Cleanup trailing whitespaces, and YAML formatting
- [ ] #6216 - This fixes next hop unit tests that segfault due to missing unit test yaml files.
- [ ] #6219 - Fixed next hop tests for out of tree builds
- [ ] #6240 - Adds strategies.yaml to install target
- [ ] #6242 - Fixes sphinx build warning with the strategies.yaml document in the admin-guide
- [ ] #6270 - LGTM: fix a comparison that is always false.
- [ ] #6279 - Update the admin-guide hierachical caching and remap.config documentation. 
- [ ] #6303 - Fixes a case where the NextHop consistent hash ring may not be completely searched.
- [ ] #6339 - Fixes an issue where NextHopSelectionStrategy did not implement a parent check.

**Comment by zwoop** [comment]
Blocks #5932

**Comment by zwoop** [comment]
All done.
