### ISSUE TITLE
⛱ Optimize HTTP/2 & HPACK

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#6496]
This is an umbrella issue for optimizing HPACK encoding & related changes.
 
I optimized HAPCK encoding, but changes are getting big. so I'll break down them small PRs and list up here.

This is performance improvement, so this doesn't block any release.

- Reduce malloc
  - [ ] ~~Perf: Fix mis-usage of Arena in HPACK: #6495~~
  - [x] Introduce LocalBuffer: #6528
  - [ ] Perf: Use LocalBuffer in HTTP/2: #6536
  - [ ] Perf: Decode XPACK String Literal without Arena: -
- Optimize HPACK Table Lookup
  - [ ] Cleanups: #6509, #6520
  - [ ] Get rid of `casecmp`: #6521
  - [ ] Optimize Static Table Lookup: -
  - [ ] Optimize Dynamic Table Lookup: -
- Optimize HTTPHdr Conversion
  - [x] Optimize HTTPHdr conversion of HTTP/2 to HTTP/1.1: #6545
  - [x] Optimize HTTPHdr conversion of HTTP/1.1 to HTTP/2: #6635
- Misc
  - [ ] Get rid of `snprintf()` to get authority: -
  - [ ] Add HTTP/2 Pseudo Headers to Well-Know-Strings: -
