### ISSUE TITLE
Outbound PROXY Protocol Support

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#7444]
ATS has Inbound PROXY Protocol v1 support from 8.0.0 and recently v2 support is added (#7339). The outbound PROXY protocol also useful.

1. Forward PROXY Protocol
Currently, the received PROXY Protocol is converted to `Forwarded` HTTP header by `proxy.config.http.insert_forwarded` config. It's useful if ATS forwards it by PROXY Protocol. 

2. Generate PROXY Protocol as LB
Not only forwarding but sending PROXY protocol from ATS would be also useful.

[*1] https://docs.trafficserver.apache.org/en/latest/admin-guide/configuration/proxy-protocol.en.html
[*2] https://docs.trafficserver.apache.org/en/latest/admin-guide/files/records.config.en.html#proxy-config-http-insert-forwarded

# TODO
- [x] Add PROXY Protocol Builder #7445
- [x] Add outbound PROXY protocol support #7446
- [ ] AuTest (if possible)
